server:
    port: 8082

spring:
    application:
        name:  service-organization
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/organizationsdb?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: toor
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
---
clients:
  service-department: http://${DEPARTMENT_HOST:localhost}:8081/v1/department
